version: '3'
networks:
  net:
    ipam:
      config:
      - subnet: 172.32.0.0/24
services:
  lin2-server:
    build:
      context: "./api-server"
    container_name: server
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      net:
        ipv4_address: 172.32.0.2
  lin2-client:
    build:
      context: "./api-client"
    container_name: client
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - "lin2-server"
    networks:
      net:
        ipv4_address: 172.32.0.3
